In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Crop_recommendation.csv')

In [4]:
df_test = pd.DataFrame()

In [5]:
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [7]:
df['label'].value_counts()

jute           100
pomegranate    100
banana         100
papaya         100
apple          100
mango          100
lentil         100
pigeonpeas     100
blackgram      100
coconut        100
muskmelon      100
kidneybeans    100
rice           100
mothbeans      100
mungbean       100
coffee         100
grapes         100
watermelon     100
maize          100
orange         100
cotton         100
chickpea       100
Name: label, dtype: int64

# X-Y split

In [8]:
x = df.loc[:, df.columns != 'label']
type(x)

pandas.core.frame.DataFrame

In [9]:
y = df.loc[:, df.columns == 'label']
labels = df['label']

In [10]:
# labels.head()
y.head()

label
0  rice
1  rice
2  rice
3  rice
4  rice

# train-test split

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [12]:
x_train.head()

N    P    K  temperature   humidity        ph    rainfall
1567  27  120  200    21.452787  90.745319  6.110219  116.703658
2031  81   36   38    23.765547  87.983299  6.334838  150.316615
2073  90   59   35    24.251335  89.864541  7.098228  175.174211
1374  81   16   45    26.904357  86.254262  6.727468   59.759800
279   47   80   77    17.182484  16.428918  7.561108   72.850173

In [13]:
y_train.head()

label
1567       apple
2031        jute
2073        jute
1374  watermelon
279     chickpea

# Standardize data

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
sc = StandardScaler().fit(x_train)

In [47]:
x_train_std = sc.transform(x_train)

In [50]:
x_test_std = sc.transform(x_test)

In [40]:
x_train

N    P    K  temperature   humidity        ph    rainfall
1567   27  120  200    21.452787  90.745319  6.110219  116.703658
2031   81   36   38    23.765547  87.983299  6.334838  150.316615
2073   90   59   35    24.251335  89.864541  7.098228  175.174211
1374   81   16   45    26.904357  86.254262  6.727468   59.759800
279    47   80   77    17.182484  16.428918  7.561108   72.850173
...   ...  ...  ...          ...        ...       ...         ...
1033  102   71   48    28.654563  79.286937  5.695268  102.463378
1731   34   68   51    27.347349  94.177567  6.687088   40.351531
763    35   64   15    28.474423  63.536045  6.500145   69.527441
835    39   65   23    25.434598  69.126134  7.685959   41.026829
1653   14   22    9    17.249446  91.137728  6.543192  112.509052

[1760 rows x 7 columns]

# Classification tree

In [37]:
from sklearn import svm

In [38]:
kernel_type = 'linear'
clf_svm_1 = svm.SVC(kernel = kernel_type, C = 0.1)
clf_svm_1.fit(x_train, y_train)

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# prediction

In [39]:
x_test

N    P    K  temperature   humidity        ph    rainfall
1320  105   14   50    26.214884  87.688398  6.419052   59.655908
1367   91   12   46    24.644585  85.499382  6.343943   48.312190
1291   14  121  203     9.724458  83.747656  6.158689   74.464111
264    52   73   79    17.257695  18.749440  7.840339   94.002872
728    32   66   17    34.946616  65.267740  7.162358   70.141514
...   ...  ...  ...          ...        ...       ...         ...
446    32   70   20    20.893427  46.248565  6.208843  195.569787
1005   93   94   53    25.866324  84.423793  6.079179  114.535750
1919  117   56   15    25.992374  77.054355  7.368258   89.118821
708    27   64   21    32.842130  68.684015  7.543804   73.671662
1546   31  130  198    21.801298  92.734467  5.554824  120.058667

[440 rows x 7 columns]

In [40]:
y_train_pred = clf_svm_1.predict(x_train)
y_test_pred = clf_svm_1.predict(x_test)

In [41]:
list(y_test_pred)

['watermelon',
 'watermelon',
 'grapes',
 'chickpea',
 'blackgram',
 'rice',
 'mothbeans',
 'kidneybeans',
 'muskmelon',
 'banana',
 'mothbeans',
 'coffee',
 'lentil',
 'mungbean',
 'mango',
 'apple',
 'coffee',
 'lentil',
 'coffee',
 'mango',
 'coconut',
 'blackgram',
 'kidneybeans',
 'jute',
 'cotton',
 'coffee',
 'lentil',
 'orange',
 'mothbeans',
 'kidneybeans',
 'pomegranate',
 'rice',
 'maize',
 'muskmelon',
 'coconut',
 'cotton',
 'mango',
 'mango',
 'watermelon',
 'mothbeans',
 'maize',
 'blackgram',
 'pigeonpeas',
 'watermelon',
 'pigeonpeas',
 'mungbean',
 'kidneybeans',
 'kidneybeans',
 'cotton',
 'mungbean',
 'mothbeans',
 'blackgram',
 'apple',
 'muskmelon',
 'pigeonpeas',
 'banana',
 'papaya',
 'mango',
 'lentil',
 'cotton',
 'orange',
 'mungbean',
 'watermelon',
 'rice',
 'muskmelon',
 'apple',
 'grapes',
 'coffee',
 'apple',
 'orange',
 'coconut',
 'pomegranate',
 'kidneybeans',
 'maize',
 'grapes',
 'mothbeans',
 'chickpea',
 'maize',
 'jute',
 'mango',
 'rice',
 'blac

# Performance

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix
import math

In [43]:
confusion_matrix(y_test, y_test_pred)

array([[18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 15,  0,  0,  0,  0,  1,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 18,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 19,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20,  0,  0,

In [44]:
accuracy_score(y_test, y_test_pred)

0.9840909090909091

In [45]:
clf_svm_1.n_support_

array([ 5, 17, 22, 17, 12, 11, 13,  8, 28, 23, 22, 24, 18, 22, 19,  9, 21,
       22, 19, 16, 22, 13])

# Grid Search

In [46]:
from sklearn.model_selection import GridSearchCV

In [47]:
param_C_list_1 = [0.001, 0.005, 0.01, 0.05, 0.1,0.2,0.5,1]
param_C_list_1

[0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.5, 1]

In [48]:
params = {'C': param_C_list_1}

In [49]:
clf_svm_1 = svm.SVC(kernel='linear')

In [50]:
svm_grid_lin = GridSearchCV(clf_svm_1,params, n_jobs = -1,
                            cv = 32, verbose=1,scoring='accuracy')

In [51]:
svm_grid_lin.fit(x_train, y_train)

Fitting 32 folds for each of 8 candidates, totalling 256 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 225 out of 256 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done 256 out of 256 | elapsed:    0.4s finished
c:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(cv=32, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [0.001, 0.005, 0.01, 0.05, 0.1, 0.2, 0.5, 1]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [52]:
svm_grid_lin.best_params_

{'C': 0.1}

In [53]:
linsvm_clf = svm_grid_lin.best_estimator_

In [54]:
accuracy_score(y_test, linsvm_clf.predict(x_test))

0.9840909090909091

In [55]:
linsvm_clf.n_support_

array([ 5, 17, 22, 17, 12, 11, 13,  8, 28, 23, 22, 24, 18, 22, 19,  9, 21,
       22, 19, 16, 22, 13])

# Saving model

In [56]:
!pip install joblib

In [57]:
import joblib

In [58]:
joblib.dump(linsvm_clf, 'svm_model.joblib')

['svm_model.joblib']

In [60]:
model = joblib.load('svm_model.joblib')

In [64]:
type(x_test)

pandas.core.frame.DataFrame

In [68]:
model.predict([x_test.iloc[1]])[0]

'watermelon'